# Generated by Django 5.0.6 on 2024-07-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musican_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_Name', models.CharField(max_length=20)),
                ('Album_Realese_Date', models.DateField(auto_now_add=True)),
                ('Rating', models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], default='1', max_length=5)),
                ('Musican', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musican_app.musican')),
            ],
        ),
    ]
