# Generated by Django 5.0.6 on 2024-07-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musican_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musican',
            name='First_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='musican',
            name='Last_Name',
            field=models.CharField(max_length=100),
        ),
    ]
